import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Top from "@/app/_component/Top";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
    weight: ["300", "500", "600"]
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`dark`}>
        <body
            className={`${inter.variable} antialiased`}
        >
        <div className={`flex flex-col h-full min-h-screen w-screen bg-nearly-white text-[14px] text-dark-blue font-inter font-medium dark:bg-nearly-black dark:text-nearly-white`}>
            <Top/>
            <div className={`flex justify-center items-center grow flex-col px-4 py-8`}>{children}
            </div>
        </div>
        </body>
        </html>
    );
}
